language: python

python:
  - "3.12"

cache: pip

install:
  - pip install -r requirements-node.txt
  - pip install -r tests/requirements.txt
  - cp tests/config_custom.txt ./config_custom.txt

#script:
#  - pyinstaller --uac-admin --log-level=INFO node.py --icon=graphics\icon.ico --hidden-import=pycryptodomex --hidden-import=PySocks

notifications:
  # slack: cryptobismuth:Mtd8QY1ElBCfM7ijzsyCE7HU
  email: false

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

script:
  - python -m pytest -v
