#!/usr/bin/env python3
"""Non-destructive one-shot migrator: legacy key=value config.txt -> modern config.toml (doc/11, doc/38).

Reuses the node's own loader (``options.Get``) so the emitted values are EXACTLY what the node would
parse — same schema coercion, same property renames — and emits ONLY the keys the operator actually set
(not the ~50 backfilled defaults), preserving the minimal-config intent. Writes valid TOML with a tiny
zero-dependency serializer (the schema is only str/int/bool/comma-list/JSON-dict), so the node runtime
gains NO new dependency (reading config.toml uses stdlib ``tomllib``).

Guarantees: never deletes or rewrites config.txt (the gpuminer / legacy_sync_probe parsers still read it);
refuses to overwrite an existing config.toml without --force; writes atomically (temp + rename); and
--check loads BOTH files through ``options.Get`` and asserts the resulting Config is identical before
writing — a self-verifying migration.

Usage:
    python scripts/migrate_config.py [--in config.txt] [--out config.toml] [--check] [--force] [--custom]
"""
import argparse
import os
import sys

# import the node's loader from the repo root regardless of cwd
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)
import options  # noqa: E402


def _present_keys(txt_path):
    """The set of schema keys the operator ACTUALLY set in the legacy file (left-hand sides), so we emit a
    minimal config.toml rather than all the backfilled defaults."""
    keys = []
    seen = set()
    with open(txt_path) as fp:
        for line in fp:
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            left = s.split("=", 1)[0].strip()
            if left in options.Get.vars and left not in seen:
                seen.add(left)
                keys.append(left)
    return keys


def _toml_str(s):
    """A TOML basic-string literal with the escapes the spec requires for our value set."""
    out = str(s).replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return '"' + out + '"'


def _toml_value(v):
    if isinstance(v, bool):              # MUST precede int (bool is an int subclass)
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join("%s = %s" % (_toml_str(k), _toml_value(val)) for k, val in v.items()) + " }"
    return _toml_str(v)                  # str (incl. the str-typed `port`, round-trips as "5658")


def build_toml(txt_path):
    """Render the operator-set keys of `txt_path` as TOML, using the loader's typed values."""
    g = options.Get()
    g.load_file(txt_path)                # apply the real schema coercion + property renames
    lines = [
        "# Bismuth node configuration (TOML — doc/11). Generated by scripts/migrate_config.py.",
        "# config.toml is preferred over the legacy config.txt when present; types are the schema types.",
        "",
    ]
    for key in _present_keys(txt_path):
        # the loaded value lives under the (possibly renamed) attribute name
        params = options.Get.vars[key]
        attr = params[1] if len(params) > 1 else key
        lines.append("%s = %s" % (key, _toml_value(getattr(g, attr))))
    return "\n".join(lines) + "\n"


def _config_equal(txt_path, toml_path):
    """Load both through Get and compare the resulting Config (minus genesis/defaults that both share)."""
    a = options.Get(); a.load_file(txt_path)
    b = options.Get(); b.load_toml(toml_path)
    return a.__dict__ == b.__dict__, a.__dict__, b.__dict__


def main(argv=None):
    ap = argparse.ArgumentParser(description="Migrate config.txt -> config.toml (non-destructive)")
    ap.add_argument("--in", dest="src", default="config.txt", help="legacy source (default: config.txt)")
    ap.add_argument("--out", dest="dst", default="config.toml", help="TOML destination (default: config.toml)")
    ap.add_argument("--force", action="store_true", help="overwrite an existing destination")
    ap.add_argument("--check", action="store_true",
                    help="verify the generated TOML loads to the same Config, do not require --force")
    ap.add_argument("--custom", action="store_true",
                    help="also migrate config_custom.txt -> config_custom.toml if present")
    args = ap.parse_args(argv)

    pairs = [(args.src, args.dst)]
    if args.custom and os.path.exists("config_custom.txt"):
        pairs.append(("config_custom.txt", "config_custom.toml"))

    for src, dst in pairs:
        if not os.path.exists(src):
            print("skip: %s does not exist" % src)
            continue
        toml_text = build_toml(src)
        tmp = dst + ".tmp"
        with open(tmp, "w") as fp:
            fp.write(toml_text)
        ok, a, b = _config_equal(src, tmp)
        if not ok:
            os.remove(tmp)
            diff = {k: (a.get(k), b.get(k)) for k in set(a) | set(b) if a.get(k) != b.get(k)}
            print("ABORT: generated %s does not round-trip to the same Config as %s\n  diff: %s" % (dst, src, diff))
            return 2
        if args.check:
            os.remove(tmp)
            print("OK (--check): %s would migrate to %s with an identical Config (%d operator keys)"
                  % (src, dst, len(_present_keys(src))))
            continue
        if os.path.exists(dst) and not args.force:
            os.remove(tmp)
            print("refuse: %s already exists (use --force to overwrite). %s left intact." % (dst, src))
            return 1
        os.replace(tmp, dst)             # atomic
        print("wrote %s (%d operator keys). %s left intact." % (dst, len(_present_keys(src)), src))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
